// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'ja'
	| 'pt-br'
	| 'tr'
	| 'vi'
	| 'zh-cn'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​d​d​ ​c​o​n​n​e​c​t​i​o​n
	 */
	addConnection: string
	/**
	 * A​d​d​ ​h​e​a​d​e​r
	 */
	addHeader: string
	/**
	 * C​h​a​n​g​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​s​e​t​t​i​n​g​s​ ​t​o​ ​a​l​l​o​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​f​r​o​m
	 */
	allowConnections: string
	/**
	 * A​l​l​o​w​ ​m​i​x​e​d​ ​c​o​n​t​e​n​t
	 */
	allowMixedContent: string
	/**
	 * A​P​I​ ​k​e​y
	 */
	apiKey: string
	/**
	 * L​e​a​v​e​ ​b​l​a​n​k​ ​f​o​r​ ​l​o​c​a​l​ ​s​e​r​v​e​r​s​ ​(​e​.​g​.​ ​l​l​a​m​a​.​c​p​p​)​ ​t​h​a​t​ ​d​o​n​'​t​ ​r​e​q​u​i​r​e​ ​a​ ​k​e​y
	 */
	apiKeyOptionalHelp: string
	/**
	 * O​p​t​i​o​n​a​l​ ​—​ ​l​e​a​v​e​ ​b​l​a​n​k​ ​f​o​r​ ​l​o​c​a​l​ ​s​e​r​v​e​r​s​ ​t​h​a​t​ ​d​o​n​'​t​ ​r​e​q​u​i​r​e​ ​a​ ​k​e​y
	 */
	apiKeyOptionalPlaceholder: string
	/**
	 * E​n​t​e​r​ ​A​P​I​ ​k​e​y​ ​(​s​t​o​r​e​d​ ​s​e​r​v​e​r​-​s​i​d​e​)
	 */
	apiKeyPlaceholder: string
	/**
	 * A​P​I​ ​k​e​y​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	apiKeyRequired: string
	/**
	 * S​e​r​v​e​r​-​s​i​d​e​ ​A​P​I​ ​k​e​y​ ​c​o​n​f​i​g​u​r​e​d​ ​v​i​a​ ​O​P​E​N​A​I​_​A​P​I​_​K​E​Y​ ​e​n​v​i​r​o​n​m​e​n​t​ ​v​a​r​i​a​b​l​e​.
	 */
	apiKeyServerSideConfigured: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e​?
	 */
	areYouSureYouWantToDeleteAllKnowledge: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s​?
	 */
	areYouSureYouWantToDeleteAllSessions: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​p​r​e​f​e​r​e​n​c​e​s​?
	 */
	areYouSureYouWantToDeleteAllPreferences: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​r​v​e​r​s​?
	 */
	areYouSureYouWantToDeleteAllServers: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​i​m​p​o​r​t​?​ ​T​h​i​s​ ​w​i​l​l​ ​o​v​e​r​w​r​i​t​e​ ​a​n​y​ ​e​x​i​s​t​i​n​g​ ​d​a​t​a
	 */
	areYouSureYouWantToImportData: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​?​
​T​h​e​ ​c​o​m​p​l​e​t​i​o​n​ ​i​n​ ​p​r​o​g​r​e​s​s​ ​w​i​l​l​ ​s​t​o​p
	 */
	areYouSureYouWantToLeave: string
	/**
	 * A​s​s​i​s​t​a​n​t
	 */
	assistant: string
	/**
	 * A​t​t​a​c​h​ ​i​m​a​g​e
	 */
	attachImage: string
	/**
	 * A​u​t​o
	 */
	automatic: string
	/**
	 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
	 */
	automaticallyCheckForUpdates: string
	/**
	 * A​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	availableModels: string
	/**
	 * B​a​s​e​ ​U​R​L
	 */
	baseUrl: string
	/**
	 * B​r​o​w​s​e​ ​t​h​e​ ​l​i​s​t​ ​o​f​ ​a​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	browseModels: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * C​a​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	cantConnectToOllamaServer: string
	/**
	 * A​l​s​o​ ​c​h​e​c​k​ ​n​o​ ​b​r​o​w​s​e​r​ ​e​x​t​e​n​s​i​o​n​s​ ​a​r​e​ ​b​l​o​c​k​i​n​g​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n
	 */
	checkBrowserExtensions: string
	/**
	 * C​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
	 */
	checkingForUpdates: string
	/**
	 * C​h​e​c​k​ ​n​o​w
	 */
	checkNow: string
	/**
	 * C​l​e​a​r
	 */
	clear: string
	/**
	 * C​o​n​f​i​r​m​ ​d​e​l​e​t​i​o​n
	 */
	confirmDeletion: string
	/**
	 * C​o​n​f​i​r​m​ ​e​d​i​t
	 */
	confirmEdit: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​t​y​p​e
	 */
	connectionType: string
	/**
	 * I​d​e​n​t​i​f​i​e​s​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​i​n​ ​t​h​e​ ​m​o​d​e​l​s​ ​l​i​s​t
	 */
	connectionLabelHelp: string
	/**
	 * C​o​n​n​e​c​t​i​n​g​.​.​.
	 */
	connecting: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​v​e​r​i​f​i​e​d​ ​a​n​d​ ​i​s​ ​r​e​a​d​y​ ​t​o​ ​u​s​e
	 */
	connectionIsVerified: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​t​o​ ​v​e​r​i​f​y​,​ ​c​h​e​c​k​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​s​e​t​t​i​n​g​s​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n
	 */
	connectionFailedToVerify: string
	/**
	 * C​o​n​t​e​n​t
	 */
	content: string
	/**
	 * C​o​n​t​r​o​l​s
	 */
	controls: string
	/**
	 * A​d​v​a​n​c​e​d​ ​c​o​n​t​r​o​l​s​ ​a​r​e​ ​c​u​r​r​e​n​t​l​y​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​O​l​l​a​m​a​ ​m​o​d​e​l​s
	 */
	controlsOnlyAvailableForOllama: string
	/**
	 * C​o​p​y
	 */
	copy: string
	/**
	 * C​o​p​y​ ​o​r​ ​e​x​p​o​r​t​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	copyOrExport: string
	/**
	 * C​o​p​y​ ​a​s​ ​M​a​r​k​d​o​w​n
	 */
	copyAsMarkdown: string
	/**
	 * C​o​p​y​ ​a​s​ ​J​S​O​N
	 */
	copyAsJson: string
	/**
	 * D​o​w​n​l​o​a​d​ ​.​m​d
	 */
	downloadMarkdown: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	couldntCheckForUpdates: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	couldntConnectToOllamaServer: string
	/**
	 * C​r​e​a​t​i​n​g​ ​a​ ​t​u​n​n​e​l
	 */
	creatingTunnel: string
	/**
	 * C​u​s​t​o​m​ ​h​e​a​d​e​r​s
	 */
	customHeaders: string
	/**
	 * C​u​s​t​o​m​ ​h​e​a​d​e​r​s​ ​m​a​y​ ​c​a​u​s​e​ ​C​O​R​S​ ​e​r​r​o​r​s​ ​w​h​e​n​ ​c​o​n​n​e​c​t​i​n​g​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​t​h​e​ ​b​r​o​w​s​e​r
	 */
	customHeadersCorsWarning: string
	/**
	 * E​x​t​r​a​ ​H​T​T​P​ ​h​e​a​d​e​r​s​ ​s​e​n​t​ ​w​i​t​h​ ​e​v​e​r​y​ ​r​e​q​u​e​s​t​ ​t​o​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	customHeadersHelp: string
	/**
	 * C​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
	 */
	currentVersion: string
	/**
	 * D​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * D​a​r​k
	 */
	dark: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * D​e​l​e​t​e​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteKnowledge: string
	/**
	 * D​e​l​e​t​e​ ​s​e​r​v​e​r
	 */
	deleteServer: string
	/**
	 * D​e​l​e​t​e​ ​s​e​s​s​i​o​n
	 */
	deleteSession: string
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d
	 */
	disconnected: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * D​o​w​n​l​o​a​d​ ​m​o​d​e​l
	 */
	downloadModel: string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * E​n​a​b​l​e​ ​r​e​a​s​o​n​i​n​g
	 */
	enableReasoning: string
	/**
	 * E​d​i​t​ ​t​i​t​l​e
	 */
	editTitle: string
	/**
	 * N​o​ ​k​n​o​w​l​e​d​g​e
	 */
	emptyKnowledge: string
	/**
	 * N​o​ ​s​e​s​s​i​o​n​s
	 */
	emptySessions: string
	/**
	 * E​r​r​o​r
	 */
	error: string
	/**
	 * E​x​p​o​r​t
	 */
	'export': string
	/**
	 * F​1​6​ ​K​V
	 */
	f16Kv: string
	/**
	 * F​r​e​q​u​e​n​c​y​ ​p​e​n​a​l​t​y
	 */
	frequencyPenalty: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	genericError: string
	/**
	 * G​o​ ​t​o​ ​d​o​w​n​l​o​a​d​s
	 */
	goToDownloads: string
	/**
	 * G​o​ ​t​o​ ​k​n​o​w​l​e​d​g​e
	 */
	goToKnowledge: string
	/**
	 * G​o​ ​t​o​ ​r​e​l​e​a​s​e​s
	 */
	goToReleases: string
	/**
	 * H​e​a​d​e​r​ ​n​a​m​e
	 */
	headerName: string
	/**
	 * H​e​a​d​e​r​ ​v​a​l​u​e
	 */
	headerValue: string
	/**
	 * H​o​w​ ​t​o​ ​o​b​t​a​i​n​ ​a​n​ ​A​P​I​ ​k​e​y​ ​f​r​o​m​ ​O​p​e​n​A​I​?
	 */
	howToObtainOpenAIKey: string
	/**
	 * H​o​w​ ​t​o​ ​u​p​d​a​t​e​ ​D​o​c​k​e​r​ ​c​o​n​t​a​i​n​e​r​?
	 */
	howToUpdateDocker: string
	/**
	 * I​m​p​o​r​t
	 */
	'import': string
	/**
	 * I​n​t​e​r​f​a​c​e
	 */
	'interface': string
	/**
	 * T​h​e​r​e​ ​w​a​s​ ​a​n​ ​i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	internalServerError: string
	/**
	 * Y​o​u​ ​a​r​e​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n
	 */
	isCurrentVersionLatest: string
	/**
	 * A​ ​n​e​w​e​r​ ​v​e​r​s​i​o​n​ ​i​s​ ​a​v​a​i​l​a​b​l​e
	 */
	isLatestVersion: string
	/**
	 * K​n​o​w​l​e​d​g​e
	 */
	knowledge: string
	/**
	 * K​n​o​w​l​e​d​g​e​ ​s​a​v​e​d
	 */
	knowledgeSaved: string
	/**
	 * L​a​b​e​l
	 */
	label: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * R​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	lastUsedModels: string
	/**
	 * L​i​g​h​t
	 */
	light: string
	/**
	 * L​o​w​ ​V​R​A​M
	 */
	lowVram: string
	/**
	 * M​a​i​n​ ​G​P​U
	 */
	mainGpu: string
	/**
	 * M​e​s​s​a​g​e​ ​o​f​ ​t​h​e​ ​d​a​y
	 */
	messageOfTheDay: string
	/**
	 * M​e​s​s​a​g​e​s
	 */
	messages: string
	/**
	 * M​i​n​ ​P
	 */
	minP: string
	/**
	 * M​i​r​o​s​t​a​t
	 */
	mirostat: string
	/**
	 * M​i​r​o​s​t​a​t​ ​E​T​A
	 */
	mirostatEta: string
	/**
	 * M​i​r​o​s​t​a​t​ ​T​a​u
	 */
	mirostatTau: string
	/**
	 * M​o​d​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	modelNotFound: string
	/**
	 * M​o​d​e​l​ ​o​p​t​i​o​n​s
	 */
	modelOptions: string
	/**
	 * {​m​o​d​e​l​}​ ​w​a​s​ ​d​o​w​n​l​o​a​d​e​d
	 * @param {string} model
	 */
	modelWasDownloaded: RequiredParams<'model'>
	/**
	 * M​o​d​e​l​ ​n​a​m​e​s​ ​f​i​l​t​e​r
	 */
	modelsFilter: string
	/**
	 * H​i​d​e​s​ ​m​o​d​e​l​ ​n​a​m​e​s​ ​t​h​a​t​ ​d​o​n​'​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​t​h​e​ ​f​i​l​t​e​r
	 */
	modelsFilterHelp: string
	/**
	 * M​o​t​d
	 */
	motd: string
	/**
	 * N​a​m​e
	 */
	name: string
	/**
	 * N​e​w​ ​k​n​o​w​l​e​d​g​e
	 */
	newKnowledge: string
	/**
	 * N​e​w​ ​s​e​s​s​i​o​n
	 */
	newSession: string
	/**
	 * N​o​ ​A​P​I​ ​k​e​y
	 */
	noApiKey: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​k​n​o​w​l​e​d​g​e​ ​o​r​ ​c​h​o​o​s​e​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noKnowledgeChosen: string
	/**
	 * N​o​ ​r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	noRecentModels: string
	/**
	 * N​o​ ​s​e​r​v​e​r​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​a​d​d​ ​o​n​e​ ​t​o​ ​s​t​a​r​t
	 */
	noServerConnections: string
	/**
	 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n​ ​o​r​ ​c​h​o​o​s​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noSessionChosen: string
	/**
	 * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
	 */
	notFound: string
	/**
	 * N​u​m​ ​b​a​t​c​h
	 */
	numBatch: string
	/**
	 * C​o​n​t​e​x​t​ ​s​i​z​e
	 */
	numCtx: string
	/**
	 * N​u​m​ ​G​P​U
	 */
	numGpu: string
	/**
	 * N​u​m​ ​k​e​e​p
	 */
	numKeep: string
	/**
	 * N​u​m​ ​p​r​e​d​i​c​t
	 */
	numPredict: string
	/**
	 * N​u​m​b​e​r​ ​o​f​ ​t​h​r​e​a​d​s
	 */
	numThread: string
	/**
	 * N​U​M​A
	 */
	numa: string
	/**
	 * O​l​l​a​m​a
	 */
	ollama: string
	/**
	 * O​l​l​a​m​a​'​s​ ​l​i​b​r​a​r​y
	 */
	ollamaLibrary: string
	/**
	 * O​p​e​n​A​I​:​ ​O​f​f​i​c​i​a​l​ ​A​P​I
	 */
	openAIOfficialAPI: string
	/**
	 * O​p​e​n​A​I​:​ ​C​o​m​p​a​t​i​b​l​e​ ​s​e​r​v​e​r​s​ ​(​i​.​e​.​ ​l​l​a​m​a​.​c​p​p​)
	 */
	openAICompatible: string
	/**
	 * L​M​ ​S​t​u​d​i​o
	 */
	lmStudio: string
	/**
	 * S​t​a​r​t​ ​t​h​e​ ​l​o​c​a​l​ ​s​e​r​v​e​r​ ​f​r​o​m​ ​L​M​ ​S​t​u​d​i​o​'​s​ ​D​e​v​e​l​o​p​e​r​ ​t​a​b​ ​(​d​e​f​a​u​l​t​ ​p​o​r​t​ ​1​2​3​4​)​.
	 */
	lmStudioBaseURLHelp: string
	/**
	 * O​t​h​e​r​ ​m​o​d​e​l​s
	 */
	otherModels: string
	/**
	 * P​e​n​a​l​i​z​e​ ​n​e​w​l​i​n​e
	 */
	penalizeNewline: string
	/**
	 * P​r​e​f​e​r​e​n​c​e​s
	 */
	preferences: string
	/**
	 * P​r​e​s​e​n​c​e​ ​p​e​n​a​l​t​y
	 */
	presencePenalty: string
	/**
	 * P​r​o​m​p​t
	 */
	prompt: string
	/**
	 * W​r​i​t​e​ ​l​i​t​e​r​a​l​l​y​ ​a​n​y​t​h​i​n​g
	 */
	promptPlaceholder: string
	/**
	 * P​u​l​l​ ​m​o​d​e​l
	 */
	pullModel: string
	/**
	 * M​o​d​e​l​ ​t​a​g​ ​(​e​.​g​.​ ​l​l​a​m​a​3​.​1​)
	 */
	pullModelPlaceholder: string
	/**
	 * P​u​l​l​i​n​g​ ​m​o​d​e​l
	 */
	pullingModel: string
	/**
	 * R​a​n​d​o​m
	 */
	random: string
	/**
	 * R​e​a​s​o​n​i​n​g
	 */
	reasoning: string
	/**
	 * T​h​i​s​ ​m​o​d​e​l​ ​m​a​y​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​r​e​a​s​o​n​i​n​g​ ​—​ ​r​e​s​p​o​n​d​e​d​ ​w​i​t​h​o​u​t​ ​i​t
	 */
	reasoningNotSupported: string
	/**
	 * R​e​f​r​e​s​h​ ​t​o​ ​u​p​d​a​t​e
	 */
	refreshToUpdate: string
	/**
	 * R​e​l​e​a​s​e​ ​h​i​s​t​o​r​y
	 */
	releaseHistory: string
	/**
	 * R​e​m​o​v​e​ ​h​e​a​d​e​r
	 */
	removeHeader: string
	/**
	 * R​e​p​e​a​t​ ​l​a​s​t​ ​N
	 */
	repeatLastN: string
	/**
	 * R​e​p​e​a​t​ ​p​e​n​a​l​t​y
	 */
	repeatPenalty: string
	/**
	 * R​e​t​r​y
	 */
	retry: string
	/**
	 * R​u​n
	 */
	run: string
	/**
	 * R​e​-​v​e​r​i​f​y
	 */
	reVerify: string
	/**
	 * R​u​n​t​i​m​e​ ​o​p​t​i​o​n​s
	 */
	runtimeOptions: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * S​e​a​r​c​h
	 */
	search: string
	/**
	 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
	 */
	searchEmpty: string
	/**
	 * S​e​e​d
	 */
	seed: string
	/**
	 * S​e​e​ ​d​o​c​s
	 */
	seeDocs: string
	/**
	 * S​e​r​v​e​r​s
	 */
	servers: string
	/**
	 * S​e​s​s​i​o​n​ ​a​f​f​i​n​i​t​y​ ​k​e​y
	 */
	sessionAffinityKey: string
	/**
	 * S​e​n​t​ ​a​s​ ​p​r​o​m​p​t​_​c​a​c​h​e​_​k​e​y​ ​w​i​t​h​ ​e​a​c​h​ ​r​e​q​u​e​s​t​.​ ​P​r​o​v​i​d​e​r​s​ ​l​i​k​e​ ​F​i​r​e​w​o​r​k​s​ ​A​I​ ​u​s​e​ ​t​h​i​s​ ​t​o​ ​r​o​u​t​e​ ​r​e​q​u​e​s​t​s​ ​t​o​ ​t​h​e​ ​s​a​m​e​ ​b​a​c​k​e​n​d​ ​f​o​r​ ​p​r​o​m​p​t​ ​c​a​c​h​e​ ​r​e​u​s​e​.
	 */
	sessionAffinityKeyHelp: string
	/**
	 * e​.​g​.​ ​h​o​l​l​a​m​a​-​s​e​s​s​i​o​n​-​1
	 */
	sessionAffinityKeyPlaceholder: string
	/**
	 * S​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​w​a​s​ ​u​p​d​a​t​e​d​ ​a​n​d​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​r​e​-​v​e​r​i​f​i​e​d​ ​i​n​ ​"​S​e​t​t​i​n​g​s​"
	 */
	serverSettingsUpdated: string
	/**
	 * S​e​s​s​i​o​n
	 */
	session: string
	/**
	 * S​e​s​s​i​o​n​s
	 */
	sessions: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	somethingWentWrong: string
	/**
	 * S​t​o​p​ ​s​e​q​u​e​n​c​e
	 */
	stop: string
	/**
	 * S​t​o​p​ ​c​o​m​p​l​e​t​i​o​n
	 */
	stopCompletion: string
	/**
	 * S​t​o​p​ ​r​e​s​p​o​n​s​e
	 */
	stopResponse: string
	/**
	 * S​u​c​c​e​s​s
	 */
	success: string
	/**
	 * S​y​s​t​e​m
	 */
	system: string
	/**
	 * S​y​s​t​e​m​ ​p​r​o​m​p​t
	 */
	systemPrompt: string
	/**
	 * S​y​s​t​e​m​ ​i​n​s​t​r​u​c​t​i​o​n​s
	 */
	systemPromptInstructions: string
	/**
	 * E​n​t​e​r​ ​s​y​s​t​e​m​ ​p​r​o​m​p​t​.​.​.
	 */
	systemPromptPlaceholder: string
	/**
	 * G​l​o​b​a​l​ ​S​y​s​t​e​m​ ​P​r​o​m​p​t
	 */
	globalSystemPrompt: string
	/**
	 * S​y​s​t​e​m​ ​P​r​o​m​p​t
	 */
	globalSystemPromptShort: string
	/**
	 * A​p​p​l​i​e​s​ ​t​o​ ​a​l​l​ ​s​e​s​s​i​o​n​s
	 */
	globalSystemPromptDescription: string
	/**
	 * S​e​s​s​i​o​n​ ​s​y​s​t​e​m​ ​p​r​o​m​p​t
	 */
	sessionSystemPrompt: string
	/**
	 * W​h​e​n​ ​b​o​t​h​ ​g​l​o​b​a​l​ ​a​n​d​ ​s​e​s​s​i​o​n​ ​p​r​o​m​p​t​s​ ​a​r​e​ ​s​e​t​,​ ​s​o​m​e​ ​m​o​d​e​l​s​ ​m​a​y​ ​p​r​i​o​r​i​t​i​z​e​ ​t​h​e​ ​l​a​s​t​ ​s​y​s​t​e​m​ ​i​n​s​t​r​u​c​t​i​o​n
	 */
	systemPromptMultipleNote: string
	/**
	 * T​e​m​p​e​r​a​t​u​r​e
	 */
	temperature: string
	/**
	 * T​F​S​ ​Z
	 */
	tfsZ: string
	/**
	 * T​o​p​ ​K
	 */
	topK: string
	/**
	 * T​o​p​ ​P
	 */
	topP: string
	/**
	 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​a​n​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​h​o​s​t​n​a​m​e​}​ ​o​r​ ​{​i​p​}​ ​t​r​y
	 * @param {string} hostname
	 * @param {string} ip
	 */
	tryingToConnectNotLocalhost: RequiredParams<'hostname' | 'ip'>
	/**
	 * T​y​p​i​c​a​l​ ​P
	 */
	typicalP: string
	/**
	 * Y​o​u​ ​h​a​v​e​ ​u​n​s​a​v​e​d​ ​c​h​a​n​g​e​s​ ​t​h​a​t​ ​w​i​l​l​ ​b​e​ ​l​o​s​t​.​ ​C​o​n​t​i​n​u​e​?
	 */
	unsavedChangesWillBeLost: string
	/**
	 * U​s​e​ ​M​L​O​C​K
	 */
	useMlock: string
	/**
	 * U​s​e​ ​M​M​A​P
	 */
	useMmap: string
	/**
	 * U​s​e​ ​m​o​d​e​l​s​ ​f​r​o​m​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	useModelsFromThisServer: string
	/**
	 * V​e​r​i​f​y
	 */
	verify: string
	/**
	 * V​e​r​s​i​o​n
	 */
	version: string
	/**
	 * V​o​c​a​b​ ​o​n​l​y
	 */
	vocabOnly: string
	/**
	 * W​r​i​t​e​ ​a​ ​p​r​o​m​p​t​ ​t​o​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	writePromptToStart: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * C​o​n​t​e​n​t​ ​c​o​p​i​e​d​,​ ​b​u​t​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	copiedNotPrivate: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​p​y​ ​c​o​n​t​e​n​t​.​ ​C​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	notCopiedNotPrivate: string
	/**
	 * I​m​p​o​r​t​ ​s​u​c​c​e​s​s​f​u​l
	 */
	importSuccess: string
	/**
	 * I​m​p​o​r​t​ ​f​a​i​l​e​d
	 */
	importError: string
	/**
	 * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	deleteSuccess: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​s​,​ ​m​o​d​e​l​ ​f​i​l​t​e​r​s​ ​a​n​d​ ​l​a​b​e​l​s
	 */
	serversDescription: string
	/**
	 * L​a​n​g​u​a​g​e​,​ ​t​h​e​m​e​,​ ​r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s​,​ ​e​t​c
	 */
	preferencesDescription: string
	/**
	 * E​n​t​i​r​e​ ​s​e​s​s​i​o​n​ ​h​i​s​t​o​r​y​,​ ​a​t​t​a​c​h​m​e​n​t​s​ ​a​n​d​ ​c​u​s​t​o​m​ ​m​o​d​e​l​ ​s​e​t​t​i​n​g​s
	 */
	sessionsDescription: string
	/**
	 * E​n​t​i​r​e​ ​k​n​o​w​l​e​d​g​e​ ​b​a​s​e
	 */
	knowledgeDescription: string
	/**
	 * S​e​s​s​i​o​n​ ​f​o​l​d​e​r​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	foldersDescription: string
	/**
	 * F​i​l​e​ ​a​t​t​a​c​h​m​e​n​t​ ​r​e​f​e​r​e​n​c​e​s​ ​a​n​d​ ​d​i​r​e​c​t​o​r​y​ ​s​e​l​e​c​t​i​o​n​s
	 */
	filesDescription: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​f​o​l​d​e​r​s​?
	 */
	areYouSureYouWantToDeleteAllFolders: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​f​i​l​e​ ​r​e​f​e​r​e​n​c​e​s​?
	 */
	areYouSureYouWantToDeleteAllFiles: string
	/**
	 * E​x​p​a​n​d​ ​s​i​d​e​b​a​r
	 */
	expandSidebar: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
	 */
	collapseSidebar: string
	/**
	 * F​o​l​d​e​r​s
	 */
	folders: string
	/**
	 * N​e​w​ ​f​o​l​d​e​r
	 */
	newFolder: string
	/**
	 * N​e​w​ ​f​o​l​d​e​r​.​.​.
	 */
	newFolderEllipsis: string
	/**
	 * D​e​l​e​t​e​ ​f​o​l​d​e​r
	 */
	deleteFolder: string
	/**
	 * F​o​l​d​e​r​ ​n​a​m​e
	 */
	folderName: string
	/**
	 * {​c​o​u​n​t​}​ ​s​e​s​s​i​o​n​s
	 * @param {number} count
	 */
	folderSessionCount: RequiredParams<'count'>
	/**
	 * M​o​v​e​ ​t​o​ ​f​o​l​d​e​r
	 */
	moveToFolder: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​f​o​l​d​e​r
	 */
	removeFromFolder: string
	/**
	 * U​n​f​i​l​e​d
	 */
	unfiled: string
	/**
	 * S​t​o​r​a​g​e​ ​i​s​ ​f​i​l​l​i​n​g​ ​u​p​.​ ​C​o​n​s​i​d​e​r​ ​o​r​g​a​n​i​z​i​n​g​ ​s​e​s​s​i​o​n​s​ ​i​n​t​o​ ​f​o​l​d​e​r​s​ ​o​r​ ​d​e​l​e​t​i​n​g​ ​o​l​d​ ​o​n​e​s​.
	 */
	storageFillingUp: string
	/**
	 * S​t​o​r​a​g​e​ ​n​e​a​r​l​y​ ​f​u​l​l​ ​—​ ​~​{​u​s​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​u​s​e​d​.​ ​D​e​l​e​t​e​ ​o​l​d​ ​s​e​s​s​i​o​n​s​ ​o​r​ ​a​r​c​h​i​v​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 * @param {string} total
	 * @param {string} used
	 */
	storageNearlyFull: RequiredParams<'total' | 'used'>
	/**
	 * S​t​o​r​a​g​e​ ​f​u​l​l​ ​(​~​{​u​s​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​)​.​ ​D​e​l​e​t​e​ ​o​l​d​ ​s​e​s​s​i​o​n​s​ ​o​r​ ​r​e​d​u​c​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​l​e​n​g​t​h​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 * @param {string} total
	 * @param {string} used
	 */
	storageFull: RequiredParams<'total' | 'used'>
	/**
	 * S​e​a​r​c​h​ ​s​e​s​s​i​o​n​s
	 */
	searchSessions: string
	/**
	 * C​l​e​a​r​ ​s​e​a​r​c​h
	 */
	clearSearch: string
	/**
	 * N​o​ ​s​e​s​s​i​o​n​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​s​e​a​r​c​h
	 */
	noSessionsMatchSearch: string
	/**
	 * S​e​l​e​c​t​ ​s​e​s​s​i​o​n
	 */
	selectSession: string
	/**
	 * S​e​l​e​c​t​ ​a​l​l
	 */
	selectAll: string
	/**
	 * D​e​s​e​l​e​c​t​ ​a​l​l
	 */
	deselectAll: string
	/**
	 * {​c​o​u​n​t​}​ ​s​e​l​e​c​t​e​d
	 * @param {number} count
	 */
	nSelected: RequiredParams<'count'>
	/**
	 * C​a​n​c​e​l​ ​s​e​l​e​c​t​i​o​n
	 */
	cancelSelection: string
	/**
	 * D​e​l​e​t​e​ ​{​c​o​u​n​t​}​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
	 * @param {number} count
	 */
	deleteNConversations: RequiredParams<'count'>
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​c​o​u​n​t​}​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 * @param {number} count
	 */
	areYouSureYouWantToDeleteNSessions: RequiredParams<'count'>
	/**
	 * S​e​a​r​c​h​ ​i​n​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	searchInConversation: string
	/**
	 * {​c​u​r​r​e​n​t​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​m​a​t​c​h​e​s
	 * @param {number} current
	 * @param {number} total
	 */
	matchCounter: RequiredParams<'current' | 'total'>
	/**
	 * P​r​e​v​i​o​u​s​ ​m​a​t​c​h
	 */
	previousMatch: string
	/**
	 * N​e​x​t​ ​m​a​t​c​h
	 */
	nextMatch: string
	/**
	 * F​i​l​e​s
	 */
	files: string
	/**
	 * B​r​o​w​s​e​ ​f​i​l​e​s
	 */
	browseFiles: string
	/**
	 * O​p​e​n​ ​f​o​l​d​e​r
	 */
	openFolder: string
	/**
	 * A​t​t​a​c​h​ ​o​n​c​e
	 */
	attachOnce: string
	/**
	 * A​t​t​a​c​h​ ​p​e​r​s​i​s​t​e​n​t​l​y
	 */
	attachPersistently: string
	/**
	 * N​o​ ​d​i​r​e​c​t​o​r​i​e​s​ ​a​r​e​ ​c​o​n​f​i​g​u​r​e​d​ ​f​o​r​ ​f​i​l​e​ ​a​c​c​e​s​s
	 */
	noFilesConfigured: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​d​i​r​e​c​t​o​r​y
	 */
	failedToLoadDirectory: string
	/**
	 * R​e​m​o​v​e​ ​f​i​l​e
	 */
	removeFile: string
	/**
	 * A​t​t​a​c​h​e​d​ ​t​o​ ​e​v​e​r​y​ ​m​e​s​s​a​g​e
	 */
	persistentFileIndicator: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​a​t​t​a​c​h​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	couldNotAttachFile: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​a​t​t​a​c​h​e​d​ ​t​o​ ​e​v​e​r​y​ ​m​e​s​s​a​g​e
	 * @param {string} name
	 */
	fileAttachedPersistently: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​a​t​t​a​c​h​e​d
	 * @param {string} name
	 */
	fileAttachedOnce: RequiredParams<'name'>
}

export type TranslationFunctions = {
	/**
	 * Add connection
	 */
	addConnection: () => LocalizedString
	/**
	 * Add header
	 */
	addHeader: () => LocalizedString
	/**
	 * Change your server settings to allow connections from
	 */
	allowConnections: () => LocalizedString
	/**
	 * Allow mixed content
	 */
	allowMixedContent: () => LocalizedString
	/**
	 * API key
	 */
	apiKey: () => LocalizedString
	/**
	 * Leave blank for local servers (e.g. llama.cpp) that don't require a key
	 */
	apiKeyOptionalHelp: () => LocalizedString
	/**
	 * Optional — leave blank for local servers that don't require a key
	 */
	apiKeyOptionalPlaceholder: () => LocalizedString
	/**
	 * Enter API key (stored server-side)
	 */
	apiKeyPlaceholder: () => LocalizedString
	/**
	 * API key is required
	 */
	apiKeyRequired: () => LocalizedString
	/**
	 * Server-side API key configured via OPENAI_API_KEY environment variable.
	 */
	apiKeyServerSideConfigured: () => LocalizedString
	/**
	 * Are you sure you want to delete all knowledge?
	 */
	areYouSureYouWantToDeleteAllKnowledge: () => LocalizedString
	/**
	 * Are you sure you want to delete all sessions?
	 */
	areYouSureYouWantToDeleteAllSessions: () => LocalizedString
	/**
	 * Are you sure you want to delete all preferences?
	 */
	areYouSureYouWantToDeleteAllPreferences: () => LocalizedString
	/**
	 * Are you sure you want to delete all servers?
	 */
	areYouSureYouWantToDeleteAllServers: () => LocalizedString
	/**
	 * Are you sure you want to import? This will overwrite any existing data
	 */
	areYouSureYouWantToImportData: () => LocalizedString
	/**
	 * Are you sure you want to leave?
The completion in progress will stop
	 */
	areYouSureYouWantToLeave: () => LocalizedString
	/**
	 * Assistant
	 */
	assistant: () => LocalizedString
	/**
	 * Attach image
	 */
	attachImage: () => LocalizedString
	/**
	 * Auto
	 */
	automatic: () => LocalizedString
	/**
	 * Automatically check for updates
	 */
	automaticallyCheckForUpdates: () => LocalizedString
	/**
	 * Available models
	 */
	availableModels: () => LocalizedString
	/**
	 * Base URL
	 */
	baseUrl: () => LocalizedString
	/**
	 * Browse the list of available models
	 */
	browseModels: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Can't connect to Ollama server
	 */
	cantConnectToOllamaServer: () => LocalizedString
	/**
	 * Also check no browser extensions are blocking the connection
	 */
	checkBrowserExtensions: () => LocalizedString
	/**
	 * Checking for updates...
	 */
	checkingForUpdates: () => LocalizedString
	/**
	 * Check now
	 */
	checkNow: () => LocalizedString
	/**
	 * Clear
	 */
	clear: () => LocalizedString
	/**
	 * Confirm deletion
	 */
	confirmDeletion: () => LocalizedString
	/**
	 * Confirm edit
	 */
	confirmEdit: () => LocalizedString
	/**
	 * Connection type
	 */
	connectionType: () => LocalizedString
	/**
	 * Identifies the connection in the models list
	 */
	connectionLabelHelp: () => LocalizedString
	/**
	 * Connecting...
	 */
	connecting: () => LocalizedString
	/**
	 * Connection has been verified and is ready to use
	 */
	connectionIsVerified: () => LocalizedString
	/**
	 * Connection failed to verify, check the connection settings and try again
	 */
	connectionFailedToVerify: () => LocalizedString
	/**
	 * Content
	 */
	content: () => LocalizedString
	/**
	 * Controls
	 */
	controls: () => LocalizedString
	/**
	 * Advanced controls are currently only available for Ollama models
	 */
	controlsOnlyAvailableForOllama: () => LocalizedString
	/**
	 * Copy
	 */
	copy: () => LocalizedString
	/**
	 * Copy or export conversation
	 */
	copyOrExport: () => LocalizedString
	/**
	 * Copy as Markdown
	 */
	copyAsMarkdown: () => LocalizedString
	/**
	 * Copy as JSON
	 */
	copyAsJson: () => LocalizedString
	/**
	 * Download .md
	 */
	downloadMarkdown: () => LocalizedString
	/**
	 * Couldn't check for updates automatically
	 */
	couldntCheckForUpdates: () => LocalizedString
	/**
	 * Couldn't connect to Ollama server
	 */
	couldntConnectToOllamaServer: () => LocalizedString
	/**
	 * Creating a tunnel
	 */
	creatingTunnel: () => LocalizedString
	/**
	 * Custom headers
	 */
	customHeaders: () => LocalizedString
	/**
	 * Custom headers may cause CORS errors when connecting directly from the browser
	 */
	customHeadersCorsWarning: () => LocalizedString
	/**
	 * Extra HTTP headers sent with every request to this server
	 */
	customHeadersHelp: () => LocalizedString
	/**
	 * Current version
	 */
	currentVersion: () => LocalizedString
	/**
	 * Danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * Dark
	 */
	dark: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Delete knowledge
	 */
	deleteKnowledge: () => LocalizedString
	/**
	 * Delete server
	 */
	deleteServer: () => LocalizedString
	/**
	 * Delete session
	 */
	deleteSession: () => LocalizedString
	/**
	 * Disconnected
	 */
	disconnected: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * Download model
	 */
	downloadModel: () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * Enable reasoning
	 */
	enableReasoning: () => LocalizedString
	/**
	 * Edit title
	 */
	editTitle: () => LocalizedString
	/**
	 * No knowledge
	 */
	emptyKnowledge: () => LocalizedString
	/**
	 * No sessions
	 */
	emptySessions: () => LocalizedString
	/**
	 * Error
	 */
	error: () => LocalizedString
	/**
	 * Export
	 */
	'export': () => LocalizedString
	/**
	 * F16 KV
	 */
	f16Kv: () => LocalizedString
	/**
	 * Frequency penalty
	 */
	frequencyPenalty: () => LocalizedString
	/**
	 * Sorry, something went wrong
	 */
	genericError: () => LocalizedString
	/**
	 * Go to downloads
	 */
	goToDownloads: () => LocalizedString
	/**
	 * Go to knowledge
	 */
	goToKnowledge: () => LocalizedString
	/**
	 * Go to releases
	 */
	goToReleases: () => LocalizedString
	/**
	 * Header name
	 */
	headerName: () => LocalizedString
	/**
	 * Header value
	 */
	headerValue: () => LocalizedString
	/**
	 * How to obtain an API key from OpenAI?
	 */
	howToObtainOpenAIKey: () => LocalizedString
	/**
	 * How to update Docker container?
	 */
	howToUpdateDocker: () => LocalizedString
	/**
	 * Import
	 */
	'import': () => LocalizedString
	/**
	 * Interface
	 */
	'interface': () => LocalizedString
	/**
	 * There was an internal server error, please try again later
	 */
	internalServerError: () => LocalizedString
	/**
	 * You are on the latest version
	 */
	isCurrentVersionLatest: () => LocalizedString
	/**
	 * A newer version is available
	 */
	isLatestVersion: () => LocalizedString
	/**
	 * Knowledge
	 */
	knowledge: () => LocalizedString
	/**
	 * Knowledge saved
	 */
	knowledgeSaved: () => LocalizedString
	/**
	 * Label
	 */
	label: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Recently used models
	 */
	lastUsedModels: () => LocalizedString
	/**
	 * Light
	 */
	light: () => LocalizedString
	/**
	 * Low VRAM
	 */
	lowVram: () => LocalizedString
	/**
	 * Main GPU
	 */
	mainGpu: () => LocalizedString
	/**
	 * Message of the day
	 */
	messageOfTheDay: () => LocalizedString
	/**
	 * Messages
	 */
	messages: () => LocalizedString
	/**
	 * Min P
	 */
	minP: () => LocalizedString
	/**
	 * Mirostat
	 */
	mirostat: () => LocalizedString
	/**
	 * Mirostat ETA
	 */
	mirostatEta: () => LocalizedString
	/**
	 * Mirostat Tau
	 */
	mirostatTau: () => LocalizedString
	/**
	 * Model not found
	 */
	modelNotFound: () => LocalizedString
	/**
	 * Model options
	 */
	modelOptions: () => LocalizedString
	/**
	 * {model} was downloaded
	 */
	modelWasDownloaded: (arg: { model: string }) => LocalizedString
	/**
	 * Model names filter
	 */
	modelsFilter: () => LocalizedString
	/**
	 * Hides model names that don't start with the filter
	 */
	modelsFilterHelp: () => LocalizedString
	/**
	 * Motd
	 */
	motd: () => LocalizedString
	/**
	 * Name
	 */
	name: () => LocalizedString
	/**
	 * New knowledge
	 */
	newKnowledge: () => LocalizedString
	/**
	 * New session
	 */
	newSession: () => LocalizedString
	/**
	 * No API key
	 */
	noApiKey: () => LocalizedString
	/**
	 * Create new knowledge or choose one from the list
	 */
	noKnowledgeChosen: () => LocalizedString
	/**
	 * No recently used models
	 */
	noRecentModels: () => LocalizedString
	/**
	 * No server connections, add one to start
	 */
	noServerConnections: () => LocalizedString
	/**
	 * Create a new session or choose an existing one from the list
	 */
	noSessionChosen: () => LocalizedString
	/**
	 * The page you are looking for does not exist
	 */
	notFound: () => LocalizedString
	/**
	 * Num batch
	 */
	numBatch: () => LocalizedString
	/**
	 * Context size
	 */
	numCtx: () => LocalizedString
	/**
	 * Num GPU
	 */
	numGpu: () => LocalizedString
	/**
	 * Num keep
	 */
	numKeep: () => LocalizedString
	/**
	 * Num predict
	 */
	numPredict: () => LocalizedString
	/**
	 * Number of threads
	 */
	numThread: () => LocalizedString
	/**
	 * NUMA
	 */
	numa: () => LocalizedString
	/**
	 * Ollama
	 */
	ollama: () => LocalizedString
	/**
	 * Ollama's library
	 */
	ollamaLibrary: () => LocalizedString
	/**
	 * OpenAI: Official API
	 */
	openAIOfficialAPI: () => LocalizedString
	/**
	 * OpenAI: Compatible servers (i.e. llama.cpp)
	 */
	openAICompatible: () => LocalizedString
	/**
	 * LM Studio
	 */
	lmStudio: () => LocalizedString
	/**
	 * Start the local server from LM Studio's Developer tab (default port 1234).
	 */
	lmStudioBaseURLHelp: () => LocalizedString
	/**
	 * Other models
	 */
	otherModels: () => LocalizedString
	/**
	 * Penalize newline
	 */
	penalizeNewline: () => LocalizedString
	/**
	 * Preferences
	 */
	preferences: () => LocalizedString
	/**
	 * Presence penalty
	 */
	presencePenalty: () => LocalizedString
	/**
	 * Prompt
	 */
	prompt: () => LocalizedString
	/**
	 * Write literally anything
	 */
	promptPlaceholder: () => LocalizedString
	/**
	 * Pull model
	 */
	pullModel: () => LocalizedString
	/**
	 * Model tag (e.g. llama3.1)
	 */
	pullModelPlaceholder: () => LocalizedString
	/**
	 * Pulling model
	 */
	pullingModel: () => LocalizedString
	/**
	 * Random
	 */
	random: () => LocalizedString
	/**
	 * Reasoning
	 */
	reasoning: () => LocalizedString
	/**
	 * This model may not support reasoning — responded without it
	 */
	reasoningNotSupported: () => LocalizedString
	/**
	 * Refresh to update
	 */
	refreshToUpdate: () => LocalizedString
	/**
	 * Release history
	 */
	releaseHistory: () => LocalizedString
	/**
	 * Remove header
	 */
	removeHeader: () => LocalizedString
	/**
	 * Repeat last N
	 */
	repeatLastN: () => LocalizedString
	/**
	 * Repeat penalty
	 */
	repeatPenalty: () => LocalizedString
	/**
	 * Retry
	 */
	retry: () => LocalizedString
	/**
	 * Run
	 */
	run: () => LocalizedString
	/**
	 * Re-verify
	 */
	reVerify: () => LocalizedString
	/**
	 * Runtime options
	 */
	runtimeOptions: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Search
	 */
	search: () => LocalizedString
	/**
	 * No results found
	 */
	searchEmpty: () => LocalizedString
	/**
	 * Seed
	 */
	seed: () => LocalizedString
	/**
	 * See docs
	 */
	seeDocs: () => LocalizedString
	/**
	 * Servers
	 */
	servers: () => LocalizedString
	/**
	 * Session affinity key
	 */
	sessionAffinityKey: () => LocalizedString
	/**
	 * Sent as prompt_cache_key with each request. Providers like Fireworks AI use this to route requests to the same backend for prompt cache reuse.
	 */
	sessionAffinityKeyHelp: () => LocalizedString
	/**
	 * e.g. hollama-session-1
	 */
	sessionAffinityKeyPlaceholder: () => LocalizedString
	/**
	 * Server configuration was updated and needs to be re-verified in "Settings"
	 */
	serverSettingsUpdated: () => LocalizedString
	/**
	 * Session
	 */
	session: () => LocalizedString
	/**
	 * Sessions
	 */
	sessions: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Sorry, something went wrong
	 */
	somethingWentWrong: () => LocalizedString
	/**
	 * Stop sequence
	 */
	stop: () => LocalizedString
	/**
	 * Stop completion
	 */
	stopCompletion: () => LocalizedString
	/**
	 * Stop response
	 */
	stopResponse: () => LocalizedString
	/**
	 * Success
	 */
	success: () => LocalizedString
	/**
	 * System
	 */
	system: () => LocalizedString
	/**
	 * System prompt
	 */
	systemPrompt: () => LocalizedString
	/**
	 * System instructions
	 */
	systemPromptInstructions: () => LocalizedString
	/**
	 * Enter system prompt...
	 */
	systemPromptPlaceholder: () => LocalizedString
	/**
	 * Global System Prompt
	 */
	globalSystemPrompt: () => LocalizedString
	/**
	 * System Prompt
	 */
	globalSystemPromptShort: () => LocalizedString
	/**
	 * Applies to all sessions
	 */
	globalSystemPromptDescription: () => LocalizedString
	/**
	 * Session system prompt
	 */
	sessionSystemPrompt: () => LocalizedString
	/**
	 * When both global and session prompts are set, some models may prioritize the last system instruction
	 */
	systemPromptMultipleNote: () => LocalizedString
	/**
	 * Temperature
	 */
	temperature: () => LocalizedString
	/**
	 * TFS Z
	 */
	tfsZ: () => LocalizedString
	/**
	 * Top K
	 */
	topK: () => LocalizedString
	/**
	 * Top P
	 */
	topP: () => LocalizedString
	/**
	 * If you want to connect to an Ollama server that is not available on {hostname} or {ip} try
	 */
	tryingToConnectNotLocalhost: (arg: { hostname: string, ip: string }) => LocalizedString
	/**
	 * Typical P
	 */
	typicalP: () => LocalizedString
	/**
	 * You have unsaved changes that will be lost. Continue?
	 */
	unsavedChangesWillBeLost: () => LocalizedString
	/**
	 * Use MLOCK
	 */
	useMlock: () => LocalizedString
	/**
	 * Use MMAP
	 */
	useMmap: () => LocalizedString
	/**
	 * Use models from this server
	 */
	useModelsFromThisServer: () => LocalizedString
	/**
	 * Verify
	 */
	verify: () => LocalizedString
	/**
	 * Version
	 */
	version: () => LocalizedString
	/**
	 * Vocab only
	 */
	vocabOnly: () => LocalizedString
	/**
	 * Write a prompt to start a new session
	 */
	writePromptToStart: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Content copied, but your connection is not private
	 */
	copiedNotPrivate: () => LocalizedString
	/**
	 * Couldn't copy content. Connection is not private
	 */
	notCopiedNotPrivate: () => LocalizedString
	/**
	 * Import successful
	 */
	importSuccess: () => LocalizedString
	/**
	 * Import failed
	 */
	importError: () => LocalizedString
	/**
	 * Deleted successfully
	 */
	deleteSuccess: () => LocalizedString
	/**
	 * Connections, model filters and labels
	 */
	serversDescription: () => LocalizedString
	/**
	 * Language, theme, recently used models, etc
	 */
	preferencesDescription: () => LocalizedString
	/**
	 * Entire session history, attachments and custom model settings
	 */
	sessionsDescription: () => LocalizedString
	/**
	 * Entire knowledge base
	 */
	knowledgeDescription: () => LocalizedString
	/**
	 * Session folder organization
	 */
	foldersDescription: () => LocalizedString
	/**
	 * File attachment references and directory selections
	 */
	filesDescription: () => LocalizedString
	/**
	 * Are you sure you want to delete all folders?
	 */
	areYouSureYouWantToDeleteAllFolders: () => LocalizedString
	/**
	 * Are you sure you want to delete all file references?
	 */
	areYouSureYouWantToDeleteAllFiles: () => LocalizedString
	/**
	 * Expand sidebar
	 */
	expandSidebar: () => LocalizedString
	/**
	 * Collapse sidebar
	 */
	collapseSidebar: () => LocalizedString
	/**
	 * Folders
	 */
	folders: () => LocalizedString
	/**
	 * New folder
	 */
	newFolder: () => LocalizedString
	/**
	 * New folder...
	 */
	newFolderEllipsis: () => LocalizedString
	/**
	 * Delete folder
	 */
	deleteFolder: () => LocalizedString
	/**
	 * Folder name
	 */
	folderName: () => LocalizedString
	/**
	 * {count} sessions
	 */
	folderSessionCount: (arg: { count: number }) => LocalizedString
	/**
	 * Move to folder
	 */
	moveToFolder: () => LocalizedString
	/**
	 * Remove from folder
	 */
	removeFromFolder: () => LocalizedString
	/**
	 * Unfiled
	 */
	unfiled: () => LocalizedString
	/**
	 * Storage is filling up. Consider organizing sessions into folders or deleting old ones.
	 */
	storageFillingUp: () => LocalizedString
	/**
	 * Storage nearly full — ~{used} of {total} used. Delete old sessions or archive conversations to continue.
	 */
	storageNearlyFull: (arg: { total: string, used: string }) => LocalizedString
	/**
	 * Storage full (~{used} of {total}). Delete old sessions or reduce conversation length to continue.
	 */
	storageFull: (arg: { total: string, used: string }) => LocalizedString
	/**
	 * Search sessions
	 */
	searchSessions: () => LocalizedString
	/**
	 * Clear search
	 */
	clearSearch: () => LocalizedString
	/**
	 * No sessions match your search
	 */
	noSessionsMatchSearch: () => LocalizedString
	/**
	 * Select session
	 */
	selectSession: () => LocalizedString
	/**
	 * Select all
	 */
	selectAll: () => LocalizedString
	/**
	 * Deselect all
	 */
	deselectAll: () => LocalizedString
	/**
	 * {count} selected
	 */
	nSelected: (arg: { count: number }) => LocalizedString
	/**
	 * Cancel selection
	 */
	cancelSelection: () => LocalizedString
	/**
	 * Delete {count} conversations
	 */
	deleteNConversations: (arg: { count: number }) => LocalizedString
	/**
	 * Are you sure you want to delete {count} conversations? This cannot be undone.
	 */
	areYouSureYouWantToDeleteNSessions: (arg: { count: number }) => LocalizedString
	/**
	 * Search in conversation
	 */
	searchInConversation: () => LocalizedString
	/**
	 * {current} of {total} matches
	 */
	matchCounter: (arg: { current: number, total: number }) => LocalizedString
	/**
	 * Previous match
	 */
	previousMatch: () => LocalizedString
	/**
	 * Next match
	 */
	nextMatch: () => LocalizedString
	/**
	 * Files
	 */
	files: () => LocalizedString
	/**
	 * Browse files
	 */
	browseFiles: () => LocalizedString
	/**
	 * Open folder
	 */
	openFolder: () => LocalizedString
	/**
	 * Attach once
	 */
	attachOnce: () => LocalizedString
	/**
	 * Attach persistently
	 */
	attachPersistently: () => LocalizedString
	/**
	 * No directories are configured for file access
	 */
	noFilesConfigured: () => LocalizedString
	/**
	 * Failed to load directory
	 */
	failedToLoadDirectory: () => LocalizedString
	/**
	 * Remove file
	 */
	removeFile: () => LocalizedString
	/**
	 * Attached to every message
	 */
	persistentFileIndicator: () => LocalizedString
	/**
	 * Could not attach {name}
	 */
	couldNotAttachFile: (arg: { name: string }) => LocalizedString
	/**
	 * {name} attached to every message
	 */
	fileAttachedPersistently: (arg: { name: string }) => LocalizedString
	/**
	 * {name} attached
	 */
	fileAttachedOnce: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
